controllers:
    resource: ../src/Controller/
    type: annotation

landing:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'report_list'

kernel:
    resource: ../src/Kernel.php
    type: annotation
